import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Login.module.css'
import { useRouter } from 'next/router'
import { useState, useEffect } from 'react'
import autenticar from './api/auth/auth'

export default function Home() {
  const router = useRouter();
  const [usuario, setUsuario] = useState("");
  const [contra, setContra] = useState("");
  const [paso, setPaso] = useState(false);
  const [paraVer, setParaVer] = useState("1")

  const enviarInfo = async (e) => {
    e.preventDefault();
    let x = await autenticar(usuario, contra);
    if(x){
        setParaVer("2")
    }else{
        setParaVer("3") // si es tres que si muestre que hubo error
        setUsuario("")
        setContra("")
    }
    setPaso(x)
};
useEffect(() => {
  if (paso === true) {
      sessionStorage.setItem("acceso", true);
      sessionStorage.setItem("usuario", usuario);
      sessionStorage.setItem("pagina", "noLogin")
      sessionStorage.setItem("modo", "false");
      console.log("Si")
      router.push("inicio")
  }
}, [paso])
  return (
    <>
      <Head>
        <title>Alix Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Logo.ico" />
      </Head>
      <form className={styles.superContainer}  onSubmit={enviarInfo}>
        <div className={styles.container}>
          <div className={styles.login}>
            <div className={styles.imagenC}> <img className={styles.logo} src="Logo.png" alt="Imagen No Encontrada"></img></div>
            <div className={styles.inputC} onChange={(ev)=>setUsuario(ev.target.value)} value={usuario}><input type="text" placeholder="Usuario"></input></div>
            <div className={styles.inputC} onChange={(ev)=>setContra(ev.target.value)} value={contra}><input type="password" placeholder="Contraseña"></input></div>
          </div>
        </div>
        <div className={styles.buttonC}>
          <button className={styles.button} type="submit">Iniciar Sesión</button>
        </div>
      </form>
    </>
  )
}
