import Bar from "@/components/bar";
import { useState, useEffect } from "react";
import Head from 'next/head'
import styles from '@/styles/Inicio.module.css'
import { onAuthStateChanged } from 'firebase/auth';
import { authG } from "../../firebase";
import { useRouter } from "next/router";

const checkAuth = (callback) => {
  return onAuthStateChanged(authG, (user) => {
    callback(user);
  });
};

export default function Inicio() {
  const [isDarkMode, setIsDarkMode] = useState(false);
  const router = useRouter();
  useEffect(() => {
    const unsubscribe = checkAuth((user) => {
      if (!user) {
        // Redirect to the login page if the user is not logged in
        router.replace('/');
      }
    });

    return () => unsubscribe();
  }, []);
  return (
    <>
      <Head>
        <title>Alix Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Logo.ico" />
      </Head>
      <Bar isDarkMode={isDarkMode} setIsDarkMode={setIsDarkMode}></Bar>
      <div className={styles.container}>
        <div className={styles.imagenC}>
          <img className={styles.imagen} src="Logo.png"></img>
        </div>
        <div className={styles.imagenC}>
          <div className={styles.mensaje}>Bienvenida a AlixShop!!!</div>
        </div>
      </div>
    </>
  )
}