import Bar from "@/components/bar";
import { useState, useEffect } from "react";
import Head from 'next/head'
import styles from '@/styles/Inicio.module.css'
import { onAuthStateChanged } from 'firebase/auth';
import { authG } from "../../firebase";
import modificarDocumento from "./api/firebase/update-data";
import { useRouter } from "next/router";

const checkAuth = (callback) => {
  return onAuthStateChanged(authG, (user) => {
    callback(user);
  });
};

export default function Inicio() {
  const [isDarkMode, setIsDarkMode] = useState(false);
  const [paso, setPaso] = useState(false)
  // para los permisos
  const [permisos, setPermisos] = useState(() => {
    if (typeof window !== 'undefined' && window.sessionStorage) {
      const all = sessionStorage.getItem('permisos');
      return JSON.parse(all)
    } else {
      return []
    }
  })
  const [dataMod, setDataMod] = useState(() => {
    if (typeof window !== 'undefined' && window.sessionStorage) {
      const all = sessionStorage.getItem('dataMod');
      return JSON.parse(all)
    } else {
      return []
    }
  })
  const [imURL, setImURL] = useState(() => {
    if (typeof window !== 'undefined' && window.sessionStorage) {
      setPaso(true)
      return sessionStorage.getItem('imURL');
    } else {
      return ""
    }
  })
  const router = useRouter();
  useEffect(() => {
    const unsubscribe = checkAuth((user) => {
      if (!user) {
        // Redirect to the login page if the user is not logged in
        router.replace('/');
      }
    });

    return () => unsubscribe();
  }, []);

  useEffect(()=>{
    if(imURL!=""&&paso==true){ // esto es que si hay que modificar y que si pasó
      if(dataMod.length>0){
        console.log("DataMod", dataMod)
        for(let i=0; i<dataMod.length; i++){
          modificarDocumento(dataMod[i].id, dataMod[i].origen, dataMod[i])
        }
        sessionStorage.setItem("dataMod", JSON.stringify([]))
        sessionStorage.setItem("imURL", "")
      }
    }else if (imURL==""&&paso==true){ // esto es que no hay nada que actualizar pero si se revisó
      console.log("No hay nada que actualizar")
    }
  },[imURL, paso, dataMod])
  return (
    <>
      <Head>
        <title>Alix Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Logo.ico" />
      </Head>
      <Bar isDarkMode={isDarkMode} setIsDarkMode={setIsDarkMode}></Bar>
      <div className={styles.container}>
        <div className={styles.imagenC}>
          <img className={styles.imagen} src="Logo.png"></img>
        </div>
        <div className={styles.imagenC2}>
          <div className={styles.mensaje}>Bienvenida a AlixShop!!!</div>
        </div>
      </div>
    </>
  )
}