import Bar from "@/components/bar";
import { useState, useEffect } from "react";
import Head from 'next/head'
import obtener from './api/firebase/get-data'
import styles from '@/styles/VerClientes.module.css'
import TablaClientes from "@/components/tablaClientes";
import CreateClientModal from "@/components/popup/modalCreateClient";
import ModalPopUp from "@/components/popup/popup";


export default function VerClientes() {
  const [isDarkMode, setIsDarkMode] = useState(false);
  const [clientes, setClientes] = useState([])
  const [buscar, setBuscar] = useState([])
  const [agregado, setAgregado] = useState(false)
  const [openPopUp, setOpenPopUp] = useState(false)
  const filtrarClientes = (valorBusqueda) => {
    return clientes.filter(cliente =>
      cliente.nombre.toLowerCase().includes(valorBusqueda.toLowerCase()) ||
      cliente.username.toLowerCase().includes(valorBusqueda.toLowerCase()) ||
      cliente.identificador.toLowerCase().includes(valorBusqueda.toLowerCase()) 
    );
  };

  const fetchData = async () => {
    try {
      const result = await obtener("clientes");
      setClientes(result);
      setBuscar(result)
    } catch (error) {
      // Handle the error if needed
      console.error("Error fetching data:", error);
    }
  };

  const Busqueda = (e) => {
    const valor = e.target.value;
    setBuscar(filtrarClientes(valor));

  }

  useEffect(() => {
    fetchData()
  }, [agregado])

  return (
    <>
      <Head>
        <title>Alix Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Logo.ico" />
      </Head>
      <Bar isDarkMode={isDarkMode} setIsDarkMode={setIsDarkMode}></Bar>
      <ModalPopUp
        openPopUp={openPopUp}
        setOpenPopUp={setOpenPopUp}
      >
        <CreateClientModal agregado={agregado} setAgregado={setAgregado} ></CreateClientModal>
      </ModalPopUp>
      <div className={styles.superContainer}>
        <div className={styles.container}>
          <div className={styles.barraClientes}>
            <div className={styles.inputC}>
              <div className={styles.square1}>Buscar</div>
              <div className={styles.square2}><textarea type="text" className={styles.inp} onChange={(e) => Busqueda(e)}></textarea></div>
            </div>
            <div className={styles.buttonC}>
              <button className={styles.button} onClick={(e) => setOpenPopUp(true)}>Agregar Cliente</button>
            </div>
          </div>
          <TablaClientes data={buscar}></TablaClientes>
        </div>
      </div>
    </>
  )
}