import Bar from "@/components/bar";
import { useState, useEffect } from "react";
import Head from 'next/head'
import obtener from './api/firebase/get-data'
import styles from '@/styles/VerClientes.module.css'
import TablaClientes from "@/components/tablaClientes";
import CreateClientModal from "@/components/popup/modalCreateClient";
import ModalPopUp from "@/components/popup/popup";
import { useRouter } from "next/router";


export default function VerPedidos() {
  const [isDarkMode, setIsDarkMode] = useState(false);
  const [aliexpress, setAliexpress] = useState([])
  const [shein, setShein] = useState([])
  const [buscar, setBuscar] = useState([])
  const [agregado, setAgregado] = useState(false)
  const [openPopUp, setOpenPopUp] = useState(false)
  const router = useRouter()
  const filtrarPedidos = (valorBusqueda) => {
    return pedidos.filter(pedido =>
      pedido.nombre.toLowerCase().includes(valorBusqueda.toLowerCase()) ||
      pedido.username.toLowerCase().includes(valorBusqueda.toLowerCase()) ||
      pedido.identificador.toLowerCase().includes(valorBusqueda.toLowerCase()) 
    );
  };

  const fetchAliexpress = async () => {
    try {
      const result = await obtener("Aliexpress");
      setAliexpress(result);
    } catch (error) {
      // Handle the error if needed
      console.error("Error fetching data:", error);
    }
  };
  const fetchShein = async () => {
    try {
      const result = await obtener("Shein");
      setAliexpress(result);
    } catch (error) {
      // Handle the error if needed
      console.error("Error fetching data:", error);
    }
  };

  const Busqueda = (e) => {
    const valor = e.target.value;
    setBuscar(filtrarPedidos(valor));

  }

  useEffect(() => {
    fetchAliexpress()
    fetchShein()
  }, [agregado])

  return (
    <>
      <Head>
        <title>Alix Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Logo.ico" />
      </Head>
      <Bar isDarkMode={isDarkMode} setIsDarkMode={setIsDarkMode}></Bar>
      <ModalPopUp
        openPopUp={openPopUp}
        setOpenPopUp={setOpenPopUp}
      >
        <CreateClientModal agregado={agregado} setAgregado={setAgregado} ></CreateClientModal>
      </ModalPopUp>
      <div className={styles.superContainer}>
        <div className={styles.container}>
          <div className={styles.barraClientes}>
            <div className={styles.inputC}>
              <div className={styles.square1}>Buscar</div>
              <div className={styles.square2}><textarea type="text" className={styles.inp}></textarea></div>
            </div>
            <div className={styles.buttonC}>
              <button className={styles.button} onClick={(e) => router.push("crearPedido")}>Agregar Pedido</button>
            </div>
          </div>
          
        </div>
      </div>
    </>
  )
}